const num = [21, 43, 55,32, 4,44,34,43];
const part = num.slice(2  , 4); //slice...............
const remove = num.splice(2 ,5);//plice...............
const remove1 = num.join(" ami ");//join...............
console.log(remove1)
// console.log(part);
console.log(num)
